version: '2.4'

services:
  frps:
    image: endoffight/frps
    container_name: frps
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - "./frps.ini:/etc/frps/frps.ini"
    mem_limit: 50M
    logging:
      options:
        max-size: '2m'
        max-file: '1'
      driver: json-file
