version: '3'

services:
  aria2:
    build:
      context: ./aria
    image: aria2:1.34
    ports:
      - "8080:80"
      - "6800:6800"
    volumes:
      - "./media:/mnt/media/"
    networks:
      - aria-net
    restart: always

networks:
  aria-net: