version: '2.4'

services:
  frpc:
    image: endoffight/frpc
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - "./frpc.ini:/etc/frpc/frpc.ini"
    mem_limit: 50M
    logging:
      options:
        max-size: '2m'
        max-file: '1'
      driver: json-file
