FROM alpine:3.10

LABEL maintainer "laogao <endoffight@gmail.com>"
LABEL keyword "alpine python scrapy git latest"

RUN set -ex && \
        apk add --no-cache python3 \
            git \
            py3-twisted \
            py3-cffi \
            py3-cryptography \
            py3-lxml && \
        git clone https://github.com/scrapy/scrapy.git /usr/src/scrapy && \
        pip3 install -r /usr/src/scrapy/requirements-py3.txt && \
        cd /usr/src/scrapy && \
        python3 setup.py install && \
        rm -rf /usr/src/scrapy

CMD ["ash"]