version: '3'

services:
  aria2:
    image: endoffight/aria2:with_nginx
    ports:
      - "8080:80"
      - "6800:6800"
    volumes:
      - "./media:/mnt/media/"
    networks:
      - aria-net
    restart: always

networks:
  aria-net: