version: '3'

services:

  mysql:
    # https://github.com/yobasystems/alpine-mariadb
    image: yobasystems/alpine-mariadb:10.3.17
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always


networks:
  db-my: