version: '3'

services:
  shadowsocks-kcp:
    image: endoffight/shadowsocks-kcp
    container_name: ss
    ports:
      - "8081:37210/tcp"
      - "8081:37210/udp"
      - "3721:38240/udp"
    environment:
      - PASSWORD=laogao
      - METHOD=chacha20-ietf-poly1305
      - KCP_PASS=blog.phpgao.com
      - KCP_ENCRYPT=aes-192
    restart: always
