version: "2.4"

services:
  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "${MONGO_IP_PORT}:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo

  mongo-express:
    image: mongo-express:0.49
    restart: always
    depends_on:
      - mongo
    ports:
      - "${MONGO_EXPRESS_IP_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo

networks:
  mongo: