version: '3'
services:
  gogsdb:
    image: yobasystems/alpine-mariadb:amd64
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    env_file:
      - ".env"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 33060:3306
    volumes:
      - db-data:/var/lib/mysql

  gogsapp:
    image: gogs/gogs
    env_file:
      - ".env"
    restart: unless-stopped
    ports:
      - "${GOGS_SSH_PORT}:22"
      - "${GOGS_HOST_PORT}:3000"
    environment:
      - RUN_CROND=true
    volumes:
      - gogs-data:/data
    depends_on:
      - gogsdb

volumes:
  gogs-data:
    driver: local
  db-data:
    driver: local